<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240226173126 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE anime (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, episodes INT NOT NULL, period INT DEFAULT NULL, description VARCHAR(250) DEFAULT NULL, pictures_id INT DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13045942BC415685 ON anime (pictures_id)');
        $this->addSql('CREATE INDEX IDX_1304594212469DE2 ON anime (category_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, userr_id INT NOT NULL, anime_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA14DF0FD358 ON note (userr_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14794BBE89 ON note (anime_id)');
        $this->addSql('CREATE TABLE pictures (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_name VARCHAR(255) NOT NULL, image_size INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(50) NOT NULL, pseudo VARCHAR(50) DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE watch_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_152B584BA76ED395 ON watch_list (user_id)');
        $this->addSql('CREATE TABLE watch_list_anime (watch_list_id INT NOT NULL, anime_id INT NOT NULL, PRIMARY KEY(watch_list_id, anime_id))');
        $this->addSql('CREATE INDEX IDX_991E82DFC4508918 ON watch_list_anime (watch_list_id)');
        $this->addSql('CREATE INDEX IDX_991E82DF794BBE89 ON watch_list_anime (anime_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE anime ADD CONSTRAINT FK_13045942BC415685 FOREIGN KEY (pictures_id) REFERENCES pictures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anime ADD CONSTRAINT FK_1304594212469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14DF0FD358 FOREIGN KEY (userr_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE watch_list ADD CONSTRAINT FK_152B584BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE watch_list_anime ADD CONSTRAINT FK_991E82DFC4508918 FOREIGN KEY (watch_list_id) REFERENCES watch_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE watch_list_anime ADD CONSTRAINT FK_991E82DF794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE anime DROP CONSTRAINT FK_13045942BC415685');
        $this->addSql('ALTER TABLE anime DROP CONSTRAINT FK_1304594212469DE2');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14DF0FD358');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14794BBE89');
        $this->addSql('ALTER TABLE watch_list DROP CONSTRAINT FK_152B584BA76ED395');
        $this->addSql('ALTER TABLE watch_list_anime DROP CONSTRAINT FK_991E82DFC4508918');
        $this->addSql('ALTER TABLE watch_list_anime DROP CONSTRAINT FK_991E82DF794BBE89');
        $this->addSql('DROP TABLE anime');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE pictures');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE watch_list');
        $this->addSql('DROP TABLE watch_list_anime');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
